### ISSUE TITLE
Manage dependencies

### ISSUE THREAD

**Issue by davidleonfdez** [Poems-AI/AI#5]
I think we should specify the Python packages required to work with this project, at least by adding a requirements.txt file.

I tend to rely on [pip-tools](https://github.com/jazzband/pip-tools) for this:
1. Define the high level requirements in a requirements.in file.
2. Generate the pinned dependencies in requirements.txt with `pip-compile`.

Later, if we needed to make this project an installable package or something we can replace the requirements.in with a setup.cfg and a setup.py.

How do you see it @ismaelfaro?

**Comment by ismaelfaro** [comment]
Sure. That is a good practice, and like you said, adding the installable files the setup.py can facilitate the people use the tools.

**Comment by ismaelfaro** [comment]
Poetry can be a good alternative too https://python-poetry.org

**Comment by davidleonfdez** [comment]
> Poetry can be a good alternative too https://python-poetry.org

Yes, we can try poetry too if you want, although I'd wait until we actually need it because the Python ecosystem is a bit unpredictable. For instance, some time ago pipenv was becoming the dominant tool and suddenly it stopped making releases for more than a year.

I've added the setup files in the linked PR.
